<Workspace Version="1.3.2.2480" X="-390.822640407177" Y="-249.389488383348" zoom="1.51051845643135" ScaleFactor="1" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="a70a87eb-2453-44d6-ac01-2610a56e54cf" type="PythonNodeModels.PythonNode" nickname="Python Script" x="792.146877887911" y="321.025549835109" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#this imports the default libraries
import clr
#adds the revit api
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
#adds the ability to use "transactions"
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
#the current revit file
doc = DocumentManager.Instance.CurrentDBDocument
#the internal value of the dimension
item = UnwrapElement(IN[0])
#the above value
name = IN[1]
#start the change
TransactionManager.Instance.EnsureInTransaction(doc)
#set the above value
item.Above = name
#end the change
TransactionManager.Instance.TransactionTaskDone()
#output something
OUT = name</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Nodes.DSModelElementSelection guid="d21fceea-2330-45c4-b99c-34c93c7ad170" type="Dynamo.Nodes.DSModelElementSelection" nickname="Select Model Element" x="424" y="261" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <instance id="d736e189-fb1e-49c3-8ee2-0a031fc77229-000340cc" />
    </Dynamo.Nodes.DSModelElementSelection>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="3770e033-37ea-4780-97d6-26f69ea82eac" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="486" y="400" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="&quot;test&quot;;" ShouldFocus="false" />
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="d21fceea-2330-45c4-b99c-34c93c7ad170" start_index="0" end="a70a87eb-2453-44d6-ac01-2610a56e54cf" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="3770e033-37ea-4780-97d6-26f69ea82eac" start_index="0" end="a70a87eb-2453-44d6-ac01-2610a56e54cf" end_index="1" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>