<Workspace Version="1.3.3.4651" X="3.21268035230196" Y="-123.087736078776" zoom="0.576369190760406" ScaleFactor="1" Name="Home" Description="" RunType="Automatic" RunPeriod="1000" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="e4310c19-8e8d-4646-8abe-a61d42d3006b" type="PythonNodeModels.PythonNode" nickname="Python Script" x="2172.6245509263" y="815.486152285312" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="true" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.GeometryConversion)
# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

from System.Collections.Generic import *

#Custom tolist definition provided by Dimitar Venkov
#https://github.com/dimven/SpringNodes
def tolist(x):
	if hasattr(x,'__iter__'): return x
	else : return [x]

elements = tolist(UnwrapElement(IN[0]))
views = tolist(UnwrapElement(IN[1]))
boundingBox = []

flag = 0;		
while flag &lt; len(elements):
	element = elements[flag]
	view = views[flag]
	boundingBox.append(element.BoundingBox[view].ToProtoType())
	flag = flag + 1

OUT = boundingBox</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="fcb6669d-9402-459a-a534-34757b1a518d" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Views.GetByType" x="760.182256402633" y="1082.7035920328" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="C:\Users\JohnPierson\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\archi-lab.net\bin\archilab.dll" function="archilab.Revit.Views.Views.GetByType@string">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <archilabUI.ViewTypesUi guid="830bfcdb-da4e-4d32-914e-59df5377b72a" type="archilabUI.ViewTypesUi" nickname="View Type" x="566.785915475752" y="1082.7035920328" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false" index="0:AreaPlan" />
    <PythonNodeModels.PythonNode guid="956a807f-4bd7-4c71-a578-0fd5d2006735" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1027.46011772301" y="1184.14539460768" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

doc = DocumentManager.Instance.CurrentDBDocument
uiapp = DocumentManager.Instance.CurrentUIApplication
app = uiapp.Application

from System.Collections.Generic import *

#Custom tolist definition provided by Dimitar Venkov
#https://github.com/dimven/SpringNodes
def tolist(x):
	if hasattr(x,'__iter__'): return x
	else : return [x]

elements = tolist(UnwrapElement(IN[0]))
levelId = []
for i in elements:
	levelId.append(i.GenLevel)



OUT = levelId</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="d2b3dd3a-bf23-42ae-bdf8-bc45dd3d9c70" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Element.Id" x="1175.35143725534" y="1185.28302014254" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="RevitNodes.dll" function="Revit.Elements.Element.Id">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="986c273a-3d16-428a-a1bf-8b26e2499401" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1398.97747208531" y="1094.80458569791" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="areaDictionary = {};&#xA;areaDictionary[areaLevelIds] = areas;" ShouldFocus="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="a257240f-57ce-43d0-ba7f-ffe0631c466f" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1911.19798309484" y="867.320348951113" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="areaDic[key];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="fcb6669d-9402-459a-a534-34757b1a518d" start_index="0" end="956a807f-4bd7-4c71-a578-0fd5d2006735" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="fcb6669d-9402-459a-a534-34757b1a518d" start_index="0" end="986c273a-3d16-428a-a1bf-8b26e2499401" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="830bfcdb-da4e-4d32-914e-59df5377b72a" start_index="0" end="fcb6669d-9402-459a-a534-34757b1a518d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="956a807f-4bd7-4c71-a578-0fd5d2006735" start_index="0" end="d2b3dd3a-bf23-42ae-bdf8-bc45dd3d9c70" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="d2b3dd3a-bf23-42ae-bdf8-bc45dd3d9c70" start_index="0" end="986c273a-3d16-428a-a1bf-8b26e2499401" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="986c273a-3d16-428a-a1bf-8b26e2499401" start_index="0" end="a257240f-57ce-43d0-ba7f-ffe0631c466f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="a257240f-57ce-43d0-ba7f-ffe0631c466f" start_index="0" end="e4310c19-8e8d-4646-8abe-a61d42d3006b" end_index="1" portType="0" />
  </Connectors>
  <Notes>
    <Dynamo.Graph.Notes.NoteModel guid="5ef6755b-71e5-4c6e-ad30-ef97dc29d3ac" text="&lt;/Title&gt;" x="1393.30859343443" y="437.173587202511" />
    <Dynamo.Graph.Notes.NoteModel guid="325e936c-5116-4767-a8ff-ce0ea942fc73" text="For changes made to Revit" x="1115.38179508446" y="554.039005444882" />
    <Dynamo.Graph.Notes.NoteModel guid="318e3ef7-b36c-456c-a43e-e43a6a4f9a7b" text="For notes and titles" x="1315.6916673128" y="554.039005444882" />
    <Dynamo.Graph.Notes.NoteModel guid="aaba4e69-0bea-4a71-b075-94fd1bc4be95" text="For sliders and other options" x="909.131523058275" y="554.039005444882" />
    <Dynamo.Graph.Notes.NoteModel guid="6d760212-d931-4eb9-b2bc-c73ec0459155" text="For selection and whatnot" x="717.766637917631" y="554.039005444882" />
    <Dynamo.Graph.Notes.NoteModel guid="7a94d1e5-e5fa-4c92-ae1f-2e0623bdd972" text="For workflow " x="530.186649577382" y="554.039005444882" />
    <Dynamo.Graph.Notes.NoteModel guid="13c464ec-3777-466d-b0b8-2104a509a360" text="&lt;Title&gt;" x="530.192691064286" y="436.113728447599" />
  </Notes>
  <Annotations>
    <Dynamo.Graph.Annotations.AnnotationModel guid="4dbcd780-0780-49ce-a264-0f679b5f798f" annotationText="Area location of Elements" left="520.192691064286" top="383.113728447599" width="947.115902370145" height="98.059858754912" fontSize="36" InitialTop="436.113728447599" InitialHeight="141.059858754912" TextblockHeight="43" backgrouund="#FF48B9FF">
      <Models ModelGuid="13c464ec-3777-466d-b0b8-2104a509a360" />
      <Models ModelGuid="5ef6755b-71e5-4c6e-ad30-ef97dc29d3ac" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="10603395-a354-4e7a-a862-4a6b02131580" annotationText="To Revit" left="1105.38179508446" top="508.039005444882" width="181" height="90" fontSize="30" InitialTop="554.039005444882" InitialHeight="140" TextblockHeight="36" backgrouund="#FFFFAA45">
      <Models ModelGuid="325e936c-5116-4767-a8ff-ce0ea942fc73" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="a2fcb445-b7bd-4980-b73e-cafe54c9709f" annotationText="Annotation" left="1305.6916673128" top="508.039005444882" width="158.296666666667" height="90" fontSize="30" InitialTop="554.039005444882" InitialHeight="140" TextblockHeight="36" backgrouund="#FF48B9FF">
      <Models ModelGuid="318e3ef7-b36c-456c-a43e-e43a6a4f9a7b" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="f88a16c7-e97c-4596-8112-7c8e763d6c63" annotationText="Control" left="899.131523058275" top="508.039005444882" width="192" height="90" fontSize="30" InitialTop="554.039005444882" InitialHeight="140" TextblockHeight="36" backgrouund="#FFC1D676">
      <Models ModelGuid="aaba4e69-0bea-4a71-b075-94fd1bc4be95" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="2a6dc367-b788-4065-ae6f-ea0f5534cad4" annotationText="Input" left="707.766637917631" top="508.039005444882" width="177" height="90" fontSize="30" InitialTop="554.039005444882" InitialHeight="140" TextblockHeight="36" backgrouund="#FFBB87C6">
      <Models ModelGuid="6d760212-d931-4eb9-b2bc-c73ec0459155" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="ef2a9c5e-86ca-487b-90a1-dc3501426b34" annotationText="Background" left="520.186649577382" top="508.039005444882" width="168.523333333333" height="90" fontSize="30" InitialTop="554.039005444882" InitialHeight="140" TextblockHeight="36" backgrouund="#FFB5B5B5">
      <Models ModelGuid="7a94d1e5-e5fa-4c92-ae1f-2e0623bdd972" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="74a20831-ab05-4f45-89fe-82b6139a14a6" annotationText="Build an area lookup dictionary" left="1017.46011772301" top="1055.80458569791" width="814.5173543623" height="222.47843444463" fontSize="24" InitialTop="1094.80458569791" InitialHeight="213.478434444627" TextblockHeight="29" backgrouund="#FFA4E1FF">
      <Models ModelGuid="956a807f-4bd7-4c71-a578-0fd5d2006735" />
      <Models ModelGuid="d2b3dd3a-bf23-42ae-bdf8-bc45dd3d9c70" />
      <Models ModelGuid="986c273a-3d16-428a-a1bf-8b26e2499401" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="d0ffdde3-9553-453d-bcbb-a015188c6c72" annotationText="Get the area's host view given the level id" left="1901.19798309484" top="771.320348951113" width="215" height="199" fontSize="24" InitialTop="867.320348951113" InitialHeight="133" TextblockHeight="86" backgrouund="#FFB5B5B5">
      <Models ModelGuid="a257240f-57ce-43d0-ba7f-ffe0631c466f" />
    </Dynamo.Graph.Annotations.AnnotationModel>
    <Dynamo.Graph.Annotations.AnnotationModel guid="f48bacdb-7cae-4d1a-97b6-f73fe4cb89a5" annotationText="Custom Bounding Box Definition" left="2162.6245509263" top="690.486152285312" width="144" height="244" fontSize="24" InitialTop="815.486152285312" InitialHeight="149" TextblockHeight="115" backgrouund="#FFA4E1FF">
      <Models ModelGuid="e4310c19-8e8d-4646-8abe-a61d42d3006b" />
    </Dynamo.Graph.Annotations.AnnotationModel>
  </Annotations>
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>